name: hexagonal_grid_widget
description: A hex layout widget with infinite omniscroll and is highly customizable. It's
  very efficent as only the hex widgets that are viewable are rendered while all others are not
version: 1.0.1
author: Jonathan Beckman <jonathantbeckman@gmail.com>
homepage: https://gitlab.com/jbeckman/hexagonal_grid_widget

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexagonal_grid: ^1.0.4
  tuple: ^1.0.2
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
